Multiple feature additions
liatrio/terraform-change-pr-commenter pull request #58
Opened 2024-03-13 15:27 UTC by someshkoli

1. add workflow link to comment
2. Add header and footer to the comment
3. quite mode. dont comment if there are no changes

2024-03-13 19:27 UTC, RobertKelly commented on index.js
> +    if (quiteMode && hasNoChanges) {
```suggestion
    if (quietMode && hasNoChanges) {
```

2024-03-13 19:27 UTC, RobertKelly commented on index.js
> +        core.info("Quite mode is enabled and there are no changes to the infrastructure.")
```suggestion
        core.info("Quiet mode is enabled and there are no changes to the infrastructure.")
```

2024-03-13 19:28 UTC, RobertKelly commented on .github/workflows/action-test.yml
> +          quite: "true"
```suggestion
          quiet: "true"
```

2024-03-13 19:29 UTC, RobertKelly commented on index.js
> +const quiteMode = core.getMultilineInput('quite');
```suggestion
const quietMode = core.getMultilineInput('quiet');
```

2024-03-13 19:30 UTC, RobertKelly requested changes
Made some suggestions: `quite` to `quiet`

2024-03-13 19:34 UTC, someshkoli commented
This pr has become absolute mess in attempt to get things working ☠️
Will raise a new one after after some cleanup

2024-03-14 09:52 UTC, someshkoli commented
Closing in prefrence to #60

2024-03-14 09:52 UTC, closed without merging